'From Cuis 5.0 of 7 November 2016 [latest update: #3685] on 21 April 2019 at 8:40:10 pm'!
!classDefinition: #OOStackElement category: #'Stack-Exercise'!
Object subclass: #OOStackElement
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Stack-Exercise'!

!OOStackElement methodsFor: 'as yet unclassified' stamp: 'C. L. 4/21/2019 18:06:13'!
previousElement
	^self subclassResponsibility.! !

!OOStackElement methodsFor: 'as yet unclassified' stamp: 'C. L. 4/21/2019 18:07:41'!
value
	^self subclassResponsibility.! !
